FROM microsoft/aspnetcore:1.1
ENV NUGET_XMLDOC_MODE skip
# Set proxy server url if your host and container is behind a proxy
#ENV http_proxy=http://proxyurl:port \
#    https_proxy=http://proxyurl:port
WORKDIR /vsdbg
RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        unzip \
    && rm -rf /var/lib/apt/lists/* \
    && curl -sSL https://aka.ms/getvsdbgsh | bash /dev/stdin -v latest -l /vsdbg

WORKDIR /app

EXPOSE 6000

ENTRYPOINT ["tail", "-f", "/dev/null"]