version: '3'

services:
  docker-run-aspnetcore:
    image: docker-run-aspnetcore 
    build:
      context: .
      dockerfile: Dockerfile
    deploy:      
      replicas: 2
    ports:
      - 6000:6000
     networks:
      - webnet
networks:
  webnet: