version: '3'
services:
  auth:
    container_name: docker-debug-aspnetcore
    image: docker-debug-aspnetcore
    build:
      context: .
      dockerfile: Dockerfile.debug
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DOTNET_USE_POLLING_FILE_WATCHER=1
    ports: 
      - "6000:6000"
    volumes: 
      - ./bin/Debug/netcoreapp1.1/publish/:/app